### ISSUE TITLE
can't comment out #include lines

### ISSUE THREAD

**Issue by burghto911** [nightrune/wrench#35] opened 2015-11-13 14:22 UTC
the following line still includes a file:

//#include "myfile.nut"

**Comment by nightrune** [comment] 2015-11-15 03:17
This is a problem with gpp. We aren't likely to fix that anytime soon. I've noticed it does this with lines like `#endif  // package name` as well.

**Comment by nightrune** [comment] 2015-11-16 22:29
@burghto911 I can't reproduce this.

**Comment by nightrune** [comment] 2015-11-16 22:50
Fixed with latest issue. Specificially the we used the -C command in gpp.

**Closed as completed by nightrune** 2015-11-16 22:50 UTC
Labels: bug
